"""Volatility-adaptive dual-EMA sniper MM — Prosperity 4 submission.

Generated by o4-mini (Round 5), calibrated backtester.
Local backtest PnL: 4,191 (10K ticks, queue modeling + qp=0.20).
Expected platform PnL: ~2,300 (1.8x ratio).
Strategy: Dual EMA with regime detection, vol-adaptive spreads,
sniping mispriced orders, secondary quotes at low inventory.
"""

import math

Time = int
Symbol = str
Product = str
Position = int
UserId = str
ObservationValue = int


class Listing:
    def __init__(self, symbol: Symbol, product: Product, denomination: Product) -> None:
        self.symbol = symbol
        self.product = product
        self.denomination = denomination


class ConversionObservation:
    def __init__(
        self,
        bidPrice: float,
        askPrice: float,
        transportFees: float,
        exportTariff: float,
        importTariff: float,
        sugarPrice: float,
        sunlightIndex: float,
    ) -> None:
        self.bidPrice = bidPrice
        self.askPrice = askPrice
        self.transportFees = transportFees
        self.exportTariff = exportTariff
        self.importTariff = importTariff
        self.sugarPrice = sugarPrice
        self.sunlightIndex = sunlightIndex


class Observation:
    def __init__(
        self,
        plainValueObservations: dict[Product, ObservationValue] | None = None,
        conversionObservations: dict[Product, ConversionObservation] | None = None,
    ) -> None:
        self.plainValueObservations = plainValueObservations or {}
        self.conversionObservations = conversionObservations or {}


class Order:
    def __init__(self, symbol: Symbol, price: int, quantity: int) -> None:
        self.symbol = symbol
        self.price = price
        self.quantity = quantity


class OrderDepth:
    def __init__(self) -> None:
        self.buy_orders: dict[int, int] = {}
        self.sell_orders: dict[int, int] = {}


class Trade:
    def __init__(
        self,
        symbol: Symbol,
        price: int,
        quantity: int,
        buyer: UserId = "",
        seller: UserId = "",
        timestamp: int = 0,
    ) -> None:
        self.symbol = symbol
        self.price = price
        self.quantity = quantity
        self.buyer = buyer
        self.seller = seller
        self.timestamp = timestamp


class TradingState:
    def __init__(
        self,
        timestamp: Time,
        traderData: str,
        listings: dict[Symbol, Listing],
        order_depths: dict[Symbol, OrderDepth],
        own_trades: dict[Symbol, list[Trade]],
        market_trades: dict[Symbol, list[Trade]],
        position: dict[Product, Position],
        observations: Observation,
    ) -> None:
        self.timestamp = timestamp
        self.traderData = traderData
        self.listings = listings
        self.order_depths = order_depths
        self.own_trades = own_trades
        self.market_trades = market_trades
        self.position = position
        self.observations = observations


# ---------------------------------------------------------------------------
# Strategy
# ---------------------------------------------------------------------------

BASE_SPREAD = 2
ORDER_SIZE = 15
SKEW_FACTOR = 0.3
UNWIND_THRESHOLD = 55
EMA_SHORT_ALPHA = 0.2
EMA_LONG_ALPHA = 0.05
SNIPE_BAND = 8
VOL_WINDOW = 20


class Trader:
    def __init__(self) -> None:
        self.ema_short: dict[str, float] = {}
        self.ema_long: dict[str, float] = {}
        self.price_history: dict[str, list[float]] = {}

    def run(self, state: TradingState) -> tuple[dict[str, list[Order]], int, str]:
        orders: dict[str, list[Order]] = {}

        for symbol, depth in state.order_depths.items():
            if not depth.buy_orders or not depth.sell_orders:
                continue

            bb = max(depth.buy_orders.keys())
            ba = min(depth.sell_orders.keys())
            mid = (bb + ba) / 2

            # Track price history
            if symbol not in self.price_history:
                self.price_history[symbol] = []
            self.price_history[symbol].append(mid)
            if len(self.price_history[symbol]) > VOL_WINDOW:
                self.price_history[symbol].pop(0)

            # Volatility
            vol = 1.0
            if len(self.price_history[symbol]) > 2:
                mean = sum(self.price_history[symbol]) / len(self.price_history[symbol])
                vol = max(
                    1.0,
                    math.sqrt(
                        sum((p - mean) ** 2 for p in self.price_history[symbol])
                        / len(self.price_history[symbol])
                    ),
                )

            pos = state.position.get(symbol, 0)
            symbol_orders: list[Order] = []

            # Unwind
            if abs(pos) > UNWIND_THRESHOLD:
                size = min(20, abs(pos) - 40)
                if pos > 0:
                    symbol_orders.append(Order(symbol, bb - 1, -size))
                else:
                    symbol_orders.append(Order(symbol, ba + 1, size))

            # Fair value
            if symbol == "EMERALDS":
                fair = 10000.0
            else:
                if symbol not in self.ema_short:
                    self.ema_short[symbol] = mid
                    self.ema_long[symbol] = mid
                else:
                    self.ema_short[symbol] = (
                        EMA_SHORT_ALPHA * mid + (1 - EMA_SHORT_ALPHA) * self.ema_short[symbol]
                    )
                    self.ema_long[symbol] = (
                        EMA_LONG_ALPHA * mid + (1 - EMA_LONG_ALPHA) * self.ema_long[symbol]
                    )
                fair = (self.ema_short[symbol] + self.ema_long[symbol]) / 2

                # Regime detection
                ema_div = abs(self.ema_short[symbol] - self.ema_long[symbol])
                if ema_div > vol * 2:
                    vol *= 1.5

            # Snipe mispriced orders
            for price in sorted(depth.sell_orders.keys()):
                if price < fair - SNIPE_BAND:
                    qty = min(abs(depth.sell_orders[price]), 20 - pos)
                    if qty > 0:
                        symbol_orders.append(Order(symbol, price, qty))
            for price in sorted(depth.buy_orders.keys(), reverse=True):
                if price > fair + SNIPE_BAND:
                    qty = min(depth.buy_orders[price], 20 + pos)
                    if qty > 0:
                        symbol_orders.append(Order(symbol, price, -qty))

            # Market making quotes
            if abs(pos) <= UNWIND_THRESHOLD:
                spread = max(2, int(BASE_SPREAD * (vol / 2)))
                skew = int(pos * SKEW_FACTOR * (1 + vol / 5))
                adj_size = max(5, int(ORDER_SIZE / (1 + vol / 10)))

                buy_price = min(int(fair) - spread // 2 - skew, bb + 1)
                sell_price = max(int(fair) + spread // 2 - skew, ba - 1)
                symbol_orders.append(Order(symbol, buy_price, adj_size))
                symbol_orders.append(Order(symbol, sell_price, -adj_size))

                # Secondary wider quotes at low inventory
                if abs(pos) < 20:
                    symbol_orders.append(Order(symbol, int(fair) - spread - skew, adj_size // 2))
                    symbol_orders.append(Order(symbol, int(fair) + spread - skew, -adj_size // 2))

            orders[symbol] = symbol_orders

        return orders, 0, ""
