"""Bifurcated skew pennying unwind — Prosperity 4 submission.

Generated by Gemini 3.1 Pro, orchestrator Round 10.
Local backtest PnL: 1,278 (2K ticks, calibrated).
Strategy: Pennying with asset-specific skew divisors and unwind thresholds.
EMERALDS: skew_div=12, unwind=60. TOMATOES: skew_div=8, unwind=50.
"""

Time = int
Symbol = str
Product = str
Position = int
UserId = str
ObservationValue = int


class Listing:
    def __init__(self, symbol: Symbol, product: Product, denomination: Product) -> None:
        self.symbol = symbol
        self.product = product
        self.denomination = denomination


class ConversionObservation:
    def __init__(
        self,
        bidPrice: float,
        askPrice: float,
        transportFees: float,
        exportTariff: float,
        importTariff: float,
        sugarPrice: float,
        sunlightIndex: float,
    ) -> None:
        self.bidPrice = bidPrice
        self.askPrice = askPrice
        self.transportFees = transportFees
        self.exportTariff = exportTariff
        self.importTariff = importTariff
        self.sugarPrice = sugarPrice
        self.sunlightIndex = sunlightIndex


class Observation:
    def __init__(
        self,
        plainValueObservations: dict[Product, ObservationValue] | None = None,
        conversionObservations: dict[Product, ConversionObservation] | None = None,
    ) -> None:
        self.plainValueObservations = plainValueObservations or {}
        self.conversionObservations = conversionObservations or {}


class Order:
    def __init__(self, symbol: Symbol, price: int, quantity: int) -> None:
        self.symbol = symbol
        self.price = price
        self.quantity = quantity


class OrderDepth:
    def __init__(self) -> None:
        self.buy_orders: dict[int, int] = {}
        self.sell_orders: dict[int, int] = {}


class Trade:
    def __init__(
        self,
        symbol: Symbol,
        price: int,
        quantity: int,
        buyer: UserId = "",
        seller: UserId = "",
        timestamp: int = 0,
    ) -> None:
        self.symbol = symbol
        self.price = price
        self.quantity = quantity
        self.buyer = buyer
        self.seller = seller
        self.timestamp = timestamp


class TradingState:
    def __init__(
        self,
        timestamp: Time,
        traderData: str,
        listings: dict[Symbol, Listing],
        order_depths: dict[Symbol, OrderDepth],
        own_trades: dict[Symbol, list[Trade]],
        market_trades: dict[Symbol, list[Trade]],
        position: dict[Product, Position],
        observations: Observation,
    ) -> None:
        self.timestamp = timestamp
        self.traderData = traderData
        self.listings = listings
        self.order_depths = order_depths
        self.own_trades = own_trades
        self.market_trades = market_trades
        self.position = position
        self.observations = observations


# ---------------------------------------------------------------------------
# Strategy
# ---------------------------------------------------------------------------

ORDER_SIZE = 19
EMERALD_SKEW_DIV = 12
EMERALD_UNWIND = 60
TOMATO_SKEW_DIV = 8
TOMATO_UNWIND = 50


class Trader:
    def run(self, state: TradingState) -> tuple[dict[str, list[Order]], int, str]:
        orders: dict[str, list[Order]] = {}

        for symbol, depth in state.order_depths.items():
            if not depth.buy_orders or not depth.sell_orders:
                continue

            bb = max(depth.buy_orders.keys())
            ba = min(depth.sell_orders.keys())
            pos = state.position.get(symbol, 0)

            if symbol == "EMERALDS":
                skew_div = EMERALD_SKEW_DIV
                unwind = EMERALD_UNWIND
            else:
                skew_div = TOMATO_SKEW_DIV
                unwind = TOMATO_UNWIND

            skew = pos // skew_div

            if pos > unwind:
                orders[symbol] = [Order(symbol, bb, -ORDER_SIZE)]
            elif pos < -unwind:
                orders[symbol] = [Order(symbol, ba, ORDER_SIZE)]
            else:
                orders[symbol] = [
                    Order(symbol, bb + 1 - skew, ORDER_SIZE),
                    Order(symbol, ba - 1 - skew, -ORDER_SIZE),
                ]

        return orders, 0, ""
