"""Calibrated pennying with aggressive unwind — Prosperity 4 submission.

Generated by Gemini 3.1 Pro (Round 1) + sweep (ema_alpha=0.20).
Local backtest PnL: 3,751 (10K ticks, queue modeling + qp=0.20).
Backtester is calibrated to ~1.3x of platform PnL.
Expected platform PnL: ~2,900.
"""

Time = int
Symbol = str
Product = str
Position = int
UserId = str
ObservationValue = int


class Listing:
    def __init__(self, symbol: Symbol, product: Product, denomination: Product) -> None:
        self.symbol = symbol
        self.product = product
        self.denomination = denomination


class ConversionObservation:
    def __init__(
        self,
        bidPrice: float,
        askPrice: float,
        transportFees: float,
        exportTariff: float,
        importTariff: float,
        sugarPrice: float,
        sunlightIndex: float,
    ) -> None:
        self.bidPrice = bidPrice
        self.askPrice = askPrice
        self.transportFees = transportFees
        self.exportTariff = exportTariff
        self.importTariff = importTariff
        self.sugarPrice = sugarPrice
        self.sunlightIndex = sunlightIndex


class Observation:
    def __init__(
        self,
        plainValueObservations: dict[Product, ObservationValue] | None = None,
        conversionObservations: dict[Product, ConversionObservation] | None = None,
    ) -> None:
        self.plainValueObservations = plainValueObservations or {}
        self.conversionObservations = conversionObservations or {}


class Order:
    def __init__(self, symbol: Symbol, price: int, quantity: int) -> None:
        self.symbol = symbol
        self.price = price
        self.quantity = quantity


class OrderDepth:
    def __init__(self) -> None:
        self.buy_orders: dict[int, int] = {}
        self.sell_orders: dict[int, int] = {}


class Trade:
    def __init__(
        self,
        symbol: Symbol,
        price: int,
        quantity: int,
        buyer: UserId = "",
        seller: UserId = "",
        timestamp: int = 0,
    ) -> None:
        self.symbol = symbol
        self.price = price
        self.quantity = quantity
        self.buyer = buyer
        self.seller = seller
        self.timestamp = timestamp


class TradingState:
    def __init__(
        self,
        timestamp: Time,
        traderData: str,
        listings: dict[Symbol, Listing],
        order_depths: dict[Symbol, OrderDepth],
        own_trades: dict[Symbol, list[Trade]],
        market_trades: dict[Symbol, list[Trade]],
        position: dict[Product, Position],
        observations: Observation,
    ) -> None:
        self.timestamp = timestamp
        self.traderData = traderData
        self.listings = listings
        self.order_depths = order_depths
        self.own_trades = own_trades
        self.market_trades = market_trades
        self.position = position
        self.observations = observations


# ---------------------------------------------------------------------------
# Strategy
# ---------------------------------------------------------------------------

MIN_EDGE = 2.0
SKEW_FACTOR = 0.3
EMA_ALPHA = 0.20
UNWIND_THRESHOLD = 55
ORDER_SIZE = 15


class Trader:
    def __init__(self) -> None:
        self.ema_prices: dict[str, float] = {}

    def run(self, state: TradingState) -> tuple[dict[str, list[Order]], int, str]:
        orders: dict[str, list[Order]] = {}

        for symbol, depth in state.order_depths.items():
            if not depth.buy_orders or not depth.sell_orders:
                continue

            bid = max(depth.buy_orders.keys())
            ask = min(depth.sell_orders.keys())
            pos = state.position.get(symbol, 0)
            mid = (bid + ask) / 2

            # Fair value
            if symbol == "EMERALDS":
                fair = 10000.0
            else:
                if symbol not in self.ema_prices:
                    self.ema_prices[symbol] = mid
                else:
                    self.ema_prices[symbol] = (
                        self.ema_prices[symbol] * (1 - EMA_ALPHA) + mid * EMA_ALPHA
                    )
                fair = self.ema_prices[symbol]

            skewed_fair = fair - pos * SKEW_FACTOR

            # Aggressive unwind
            if abs(pos) >= UNWIND_THRESHOLD:
                size = min(ORDER_SIZE, abs(pos))
                if pos > 0:
                    orders[symbol] = [Order(symbol, bid, -size)]
                else:
                    orders[symbol] = [Order(symbol, ask, size)]
                continue

            # Pennying with edge checks
            symbol_orders: list[Order] = []
            remaining_buy = 80 - pos
            remaining_sell = 80 + pos

            if bid + 1 < skewed_fair - MIN_EDGE and remaining_buy > 0:
                symbol_orders.append(Order(symbol, bid + 1, min(ORDER_SIZE, remaining_buy)))
            if ask - 1 > skewed_fair + MIN_EDGE and remaining_sell > 0:
                symbol_orders.append(Order(symbol, ask - 1, -min(ORDER_SIZE, remaining_sell)))

            orders[symbol] = symbol_orders

        return orders, 0, ""
