"""Nonlinear skew dynamic sizing MM — Prosperity 4 submission.

Generated by Gemini 3.1 Pro (Round 4) + parameter sweep.
Local backtest PnL: 15,897 (10K ticks, jmerle semantics).
Strategy: OBI-adjusted fair value, nonlinear inventory skew, 3-layer maker,
market taking, dynamic sizing, aggressive unwind.
"""

Time = int
Symbol = str
Product = str
Position = int
UserId = str
ObservationValue = int


class Listing:
    def __init__(self, symbol: Symbol, product: Product, denomination: Product) -> None:
        self.symbol = symbol
        self.product = product
        self.denomination = denomination


class ConversionObservation:
    def __init__(
        self,
        bidPrice: float,
        askPrice: float,
        transportFees: float,
        exportTariff: float,
        importTariff: float,
        sugarPrice: float,
        sunlightIndex: float,
    ) -> None:
        self.bidPrice = bidPrice
        self.askPrice = askPrice
        self.transportFees = transportFees
        self.exportTariff = exportTariff
        self.importTariff = importTariff
        self.sugarPrice = sugarPrice
        self.sunlightIndex = sunlightIndex


class Observation:
    def __init__(
        self,
        plainValueObservations: dict[Product, ObservationValue] | None = None,
        conversionObservations: dict[Product, ConversionObservation] | None = None,
    ) -> None:
        self.plainValueObservations = plainValueObservations or {}
        self.conversionObservations = conversionObservations or {}


class Order:
    def __init__(self, symbol: Symbol, price: int, quantity: int) -> None:
        self.symbol = symbol
        self.price = price
        self.quantity = quantity


class OrderDepth:
    def __init__(self) -> None:
        self.buy_orders: dict[int, int] = {}
        self.sell_orders: dict[int, int] = {}


class Trade:
    def __init__(
        self,
        symbol: Symbol,
        price: int,
        quantity: int,
        buyer: UserId = "",
        seller: UserId = "",
        timestamp: int = 0,
    ) -> None:
        self.symbol = symbol
        self.price = price
        self.quantity = quantity
        self.buyer = buyer
        self.seller = seller
        self.timestamp = timestamp


class TradingState:
    def __init__(
        self,
        timestamp: Time,
        traderData: str,
        listings: dict[Symbol, Listing],
        order_depths: dict[Symbol, OrderDepth],
        own_trades: dict[Symbol, list[Trade]],
        market_trades: dict[Symbol, list[Trade]],
        position: dict[Product, Position],
        observations: Observation,
    ) -> None:
        self.timestamp = timestamp
        self.traderData = traderData
        self.listings = listings
        self.order_depths = order_depths
        self.own_trades = own_trades
        self.market_trades = market_trades
        self.position = position
        self.observations = observations


# ---------------------------------------------------------------------------
# Strategy
# ---------------------------------------------------------------------------

EMA_ALPHA = 0.15
SKEW_POWER = 2.0
SKEW_FACTOR = 0.5
BASE_SIZE = 15
MIN_SIZE = 5
TAKE_THRESHOLD = 3
UNWIND_THRESHOLD = 60
OBI_WEIGHT = 0.3


class Trader:
    def __init__(self) -> None:
        self.ema_values: dict[str, float] = {}

    def run(self, state: TradingState) -> tuple[dict[str, list[Order]], int, str]:
        orders: dict[str, list[Order]] = {}

        for symbol, depth in state.order_depths.items():
            if not depth.buy_orders or not depth.sell_orders:
                continue

            pos = state.position.get(symbol, 0)
            abs_pos = abs(pos)
            bb = max(depth.buy_orders.keys())
            ba = min(depth.sell_orders.keys())

            # Fair value
            if symbol == "EMERALDS":
                fv = 10000.0
            else:
                mid = (bb + ba) / 2
                if symbol not in self.ema_values:
                    self.ema_values[symbol] = mid
                self.ema_values[symbol] = (
                    EMA_ALPHA * mid + (1 - EMA_ALPHA) * self.ema_values[symbol]
                )
                fv = self.ema_values[symbol]

            # OBI adjustment
            bid_vol = sum(depth.buy_orders.values())
            ask_vol = sum(-v for v in depth.sell_orders.values())
            if bid_vol + ask_vol > 0:
                obi = (bid_vol - ask_vol) / (bid_vol + ask_vol)
                fv += obi * OBI_WEIGHT

            # Nonlinear skew
            sign = 1 if pos > 0 else -1
            skew = sign * (abs_pos**SKEW_POWER) * SKEW_FACTOR / 100
            adjusted_fv = fv - skew

            symbol_orders: list[Order] = []

            # Dynamic sizing
            bid_size = max(MIN_SIZE, BASE_SIZE - int(max(0, pos) * 0.2))
            ask_size = max(MIN_SIZE, BASE_SIZE - int(max(0, -pos) * 0.2))

            # Aggressive unwind
            if abs_pos >= UNWIND_THRESHOLD:
                if pos > 0:
                    symbol_orders.append(Order(symbol, bb, -min(20, abs_pos - 40)))
                else:
                    symbol_orders.append(Order(symbol, ba, min(20, abs_pos - 40)))

            # Market taking
            if ba <= adjusted_fv - TAKE_THRESHOLD:
                symbol_orders.append(Order(symbol, ba, min(bid_size, 20)))
            if bb >= adjusted_fv + TAKE_THRESHOLD:
                symbol_orders.append(Order(symbol, bb, -min(ask_size, 20)))

            # 3-layer maker orders
            for i in range(3):
                bp = min(bb + 1 + i, int(adjusted_fv) - 1)
                ap = max(ba - 1 - i, int(adjusted_fv) + 1)
                symbol_orders.append(Order(symbol, bp, max(MIN_SIZE, bid_size - i * 2)))
                symbol_orders.append(Order(symbol, ap, -max(MIN_SIZE, ask_size - i * 2)))

            orders[symbol] = symbol_orders[:20]

        return orders, 0, ""
