"""Pennying dynamic inventory MM — Prosperity 4 submission.

Generated by Gemini 3.1 Pro (Round 1) + parameter sweep (unwind_threshold=40).
Local backtest PnL: 23,014 (10K ticks).
Strategy: Pennying with EMA fair value for TOMATOES, non-linear inventory skew,
aggressive unwind above threshold.
"""

Time = int
Symbol = str
Product = str
Position = int
UserId = str
ObservationValue = int


class Listing:
    def __init__(self, symbol: Symbol, product: Product, denomination: Product) -> None:
        self.symbol = symbol
        self.product = product
        self.denomination = denomination


class ConversionObservation:
    def __init__(
        self,
        bidPrice: float,
        askPrice: float,
        transportFees: float,
        exportTariff: float,
        importTariff: float,
        sugarPrice: float,
        sunlightIndex: float,
    ) -> None:
        self.bidPrice = bidPrice
        self.askPrice = askPrice
        self.transportFees = transportFees
        self.exportTariff = exportTariff
        self.importTariff = importTariff
        self.sugarPrice = sugarPrice
        self.sunlightIndex = sunlightIndex


class Observation:
    def __init__(
        self,
        plainValueObservations: dict[Product, ObservationValue] | None = None,
        conversionObservations: dict[Product, ConversionObservation] | None = None,
    ) -> None:
        self.plainValueObservations = plainValueObservations or {}
        self.conversionObservations = conversionObservations or {}


class Order:
    def __init__(self, symbol: Symbol, price: int, quantity: int) -> None:
        self.symbol = symbol
        self.price = price
        self.quantity = quantity


class OrderDepth:
    def __init__(self) -> None:
        self.buy_orders: dict[int, int] = {}
        self.sell_orders: dict[int, int] = {}


class Trade:
    def __init__(
        self,
        symbol: Symbol,
        price: int,
        quantity: int,
        buyer: UserId = "",
        seller: UserId = "",
        timestamp: int = 0,
    ) -> None:
        self.symbol = symbol
        self.price = price
        self.quantity = quantity
        self.buyer = buyer
        self.seller = seller
        self.timestamp = timestamp


class TradingState:
    def __init__(
        self,
        timestamp: Time,
        traderData: str,
        listings: dict[Symbol, Listing],
        order_depths: dict[Symbol, OrderDepth],
        own_trades: dict[Symbol, list[Trade]],
        market_trades: dict[Symbol, list[Trade]],
        position: dict[Product, Position],
        observations: Observation,
    ) -> None:
        self.timestamp = timestamp
        self.traderData = traderData
        self.listings = listings
        self.order_depths = order_depths
        self.own_trades = own_trades
        self.market_trades = market_trades
        self.position = position
        self.observations = observations


# ---------------------------------------------------------------------------
# Strategy
# ---------------------------------------------------------------------------

MAX_ORDER_SIZE = 15
EMA_ALPHA = 0.15
MILD_SKEW = 0.2
AGGRESSIVE_SKEW = 0.8
UNWIND_THRESHOLD = 40
POSITION_LIMIT = 80


class Trader:
    def __init__(self) -> None:
        self.ema_values: dict[str, float] = {}

    def run(self, state: TradingState) -> tuple[dict[str, list[Order]], int, str]:
        orders: dict[str, list[Order]] = {}

        for symbol, depth in state.order_depths.items():
            if not depth.buy_orders or not depth.sell_orders:
                continue

            bid = max(depth.buy_orders.keys())
            ask = min(depth.sell_orders.keys())
            pos = state.position.get(symbol, 0)
            abs_pos = abs(pos)

            # Fair value
            if symbol == "EMERALDS":
                fair_value = 10000.0
            else:
                mid = (bid + ask) / 2
                if symbol not in self.ema_values:
                    self.ema_values[symbol] = mid
                self.ema_values[symbol] = (
                    EMA_ALPHA * mid + (1 - EMA_ALPHA) * self.ema_values[symbol]
                )
                fair_value = self.ema_values[symbol]

            remaining_capacity = POSITION_LIMIT - abs_pos
            order_size = min(MAX_ORDER_SIZE, remaining_capacity)

            # Aggressive unwind
            if abs_pos > 60:
                if pos > 0:
                    orders[symbol] = [Order(symbol, bid, -min(order_size, pos))]
                else:
                    orders[symbol] = [Order(symbol, ask, min(order_size, -pos))]
                continue

            # Non-linear inventory skew
            skew_factor = MILD_SKEW if abs_pos < UNWIND_THRESHOLD else AGGRESSIVE_SKEW
            skew = pos * skew_factor

            # Pennying with fair value constraint
            buy_price = int(min(bid + 1 - skew, fair_value - 1))
            sell_price = int(max(ask - 1 - skew, fair_value + 1))

            order_list: list[Order] = []
            if pos < POSITION_LIMIT and buy_price <= bid + 1:
                order_list.append(Order(symbol, buy_price, order_size))
            if pos > -POSITION_LIMIT and sell_price >= ask - 1:
                order_list.append(Order(symbol, sell_price, -order_size))

            if order_list:
                orders[symbol] = order_list

        return orders, 0, ""
