"""Aggressive skew and unwind market maker — Prosperity 4 submission.

Generated by Gemini 3.1 Pro (thinking), orchestrator Round 2.
Local backtest PnL: 1,336 (2K ticks, calibrated, ~1600-1800 expected on platform).
Strategy: Tight pennying, EMA for TOMATOES, aggressive inventory skew (0.75),
unwind above 50 by crossing spread.
"""

Time = int
Symbol = str
Product = str
Position = int
UserId = str
ObservationValue = int


class Listing:
    def __init__(self, symbol: Symbol, product: Product, denomination: Product) -> None:
        self.symbol = symbol
        self.product = product
        self.denomination = denomination


class ConversionObservation:
    def __init__(
        self,
        bidPrice: float,
        askPrice: float,
        transportFees: float,
        exportTariff: float,
        importTariff: float,
        sugarPrice: float,
        sunlightIndex: float,
    ) -> None:
        self.bidPrice = bidPrice
        self.askPrice = askPrice
        self.transportFees = transportFees
        self.exportTariff = exportTariff
        self.importTariff = importTariff
        self.sugarPrice = sugarPrice
        self.sunlightIndex = sunlightIndex


class Observation:
    def __init__(
        self,
        plainValueObservations: dict[Product, ObservationValue] | None = None,
        conversionObservations: dict[Product, ConversionObservation] | None = None,
    ) -> None:
        self.plainValueObservations = plainValueObservations or {}
        self.conversionObservations = conversionObservations or {}


class Order:
    def __init__(self, symbol: Symbol, price: int, quantity: int) -> None:
        self.symbol = symbol
        self.price = price
        self.quantity = quantity


class OrderDepth:
    def __init__(self) -> None:
        self.buy_orders: dict[int, int] = {}
        self.sell_orders: dict[int, int] = {}


class Trade:
    def __init__(
        self,
        symbol: Symbol,
        price: int,
        quantity: int,
        buyer: UserId = "",
        seller: UserId = "",
        timestamp: int = 0,
    ) -> None:
        self.symbol = symbol
        self.price = price
        self.quantity = quantity
        self.buyer = buyer
        self.seller = seller
        self.timestamp = timestamp


class TradingState:
    def __init__(
        self,
        timestamp: Time,
        traderData: str,
        listings: dict[Symbol, Listing],
        order_depths: dict[Symbol, OrderDepth],
        own_trades: dict[Symbol, list[Trade]],
        market_trades: dict[Symbol, list[Trade]],
        position: dict[Product, Position],
        observations: Observation,
    ) -> None:
        self.timestamp = timestamp
        self.traderData = traderData
        self.listings = listings
        self.order_depths = order_depths
        self.own_trades = own_trades
        self.market_trades = market_trades
        self.position = position
        self.observations = observations


# ---------------------------------------------------------------------------
# Strategy
# ---------------------------------------------------------------------------

ORDER_SIZE = 15
UNWIND_SIZE = 20
UNWIND_THRESHOLD = 50
EMA_ALPHA = 0.20


class Trader:
    def __init__(self) -> None:
        self.ema_price: dict[str, float] = {}

    def run(self, state: TradingState) -> tuple[dict[str, list[Order]], int, str]:
        orders: dict[str, list[Order]] = {}

        for symbol, depth in state.order_depths.items():
            if not depth.buy_orders or not depth.sell_orders:
                continue

            bb = max(depth.buy_orders.keys())
            ba = min(depth.sell_orders.keys())
            pos = state.position.get(symbol, 0)

            # Fair value
            if symbol == "EMERALDS":
                fair = 10000.0
            else:
                mid = (bb + ba) / 2
                if symbol not in self.ema_price:
                    self.ema_price[symbol] = mid
                else:
                    self.ema_price[symbol] = (
                        EMA_ALPHA * mid + (1 - EMA_ALPHA) * self.ema_price[symbol]
                    )
                fair = self.ema_price[symbol]

            # Unwind if inventory too large
            if abs(pos) > UNWIND_THRESHOLD:
                if pos > UNWIND_THRESHOLD:
                    orders[symbol] = [Order(symbol, bb, -UNWIND_SIZE)]
                else:
                    orders[symbol] = [Order(symbol, ba, UNWIND_SIZE)]
                continue

            # Aggressive skew + pennying
            skew = int(pos * 0.75)
            buy_price = min(bb + 1 - skew, int(fair) - 1)
            sell_price = max(ba - 1 - skew, int(fair) + 1)

            orders[symbol] = [
                Order(symbol, buy_price, ORDER_SIZE),
                Order(symbol, sell_price, -ORDER_SIZE),
            ]

        return orders, 0, ""
