"""Volatility-adaptive microprice sniper — Prosperity 4 submission.

Generated by Gemini 3.1 Pro (Round 4), jmerle-compatible backtester.
Local backtest PnL: 15,503 (10K ticks, jmerle matching).
Expected platform PnL: ~2,770 (5.6x ratio).
Strategy: Microprice fair value, OBI-adjusted, momentum-weighted EMA,
volatility-adaptive edge, pennying + sniping, aggressive unwind.
"""

import math

Time = int
Symbol = str
Product = str
Position = int
UserId = str
ObservationValue = int


class Listing:
    def __init__(self, symbol: Symbol, product: Product, denomination: Product) -> None:
        self.symbol = symbol
        self.product = product
        self.denomination = denomination


class ConversionObservation:
    def __init__(
        self,
        bidPrice: float,
        askPrice: float,
        transportFees: float,
        exportTariff: float,
        importTariff: float,
        sugarPrice: float,
        sunlightIndex: float,
    ) -> None:
        self.bidPrice = bidPrice
        self.askPrice = askPrice
        self.transportFees = transportFees
        self.exportTariff = exportTariff
        self.importTariff = importTariff
        self.sugarPrice = sugarPrice
        self.sunlightIndex = sunlightIndex


class Observation:
    def __init__(
        self,
        plainValueObservations: dict[Product, ObservationValue] | None = None,
        conversionObservations: dict[Product, ConversionObservation] | None = None,
    ) -> None:
        self.plainValueObservations = plainValueObservations or {}
        self.conversionObservations = conversionObservations or {}


class Order:
    def __init__(self, symbol: Symbol, price: int, quantity: int) -> None:
        self.symbol = symbol
        self.price = price
        self.quantity = quantity


class OrderDepth:
    def __init__(self) -> None:
        self.buy_orders: dict[int, int] = {}
        self.sell_orders: dict[int, int] = {}


class Trade:
    def __init__(
        self,
        symbol: Symbol,
        price: int,
        quantity: int,
        buyer: UserId = "",
        seller: UserId = "",
        timestamp: int = 0,
    ) -> None:
        self.symbol = symbol
        self.price = price
        self.quantity = quantity
        self.buyer = buyer
        self.seller = seller
        self.timestamp = timestamp


class TradingState:
    def __init__(
        self,
        timestamp: Time,
        traderData: str,
        listings: dict[Symbol, Listing],
        order_depths: dict[Symbol, OrderDepth],
        own_trades: dict[Symbol, list[Trade]],
        market_trades: dict[Symbol, list[Trade]],
        position: dict[Product, Position],
        observations: Observation,
    ) -> None:
        self.timestamp = timestamp
        self.traderData = traderData
        self.listings = listings
        self.order_depths = order_depths
        self.own_trades = own_trades
        self.market_trades = market_trades
        self.position = position
        self.observations = observations


# ---------------------------------------------------------------------------
# Strategy
# ---------------------------------------------------------------------------

BASE_SIZE = 15
SKEW_FACTOR = 0.5
EMA_ALPHA = 0.15
MOMENTUM_WEIGHT = 0.3
VOL_WINDOW = 10
EDGE_MULTIPLIER = 1.5
OBI_THRESHOLD = 0.7
UNWIND_THRESHOLD = 50


class Trader:
    def __init__(self) -> None:
        self.tom_ema: float | None = None
        self.tom_momentum: float = 0.0
        self.mid_history: dict[str, list[float]] = {"TOMATOES": [], "EMERALDS": []}

    def run(self, state: TradingState) -> tuple[dict[str, list[Order]], int, str]:
        orders: dict[str, list[Order]] = {}

        for symbol in ["TOMATOES", "EMERALDS"]:
            depth = state.order_depths.get(symbol)
            if not depth or not depth.buy_orders or not depth.sell_orders:
                continue

            pos = state.position.get(symbol, 0)
            bb = max(depth.buy_orders.keys())
            ba = min(depth.sell_orders.keys())

            # Unwind mode
            if abs(pos) > UNWIND_THRESHOLD:
                if pos > 0:
                    orders[symbol] = [Order(symbol, bb, -min(20, pos))]
                else:
                    orders[symbol] = [Order(symbol, ba, min(20, -pos))]
                continue

            # Microprice (volume-weighted)
            bid_vol = sum(depth.buy_orders.values())
            ask_vol = sum(-v for v in depth.sell_orders.values())
            total_vol = bid_vol + ask_vol
            if total_vol > 0:
                microprice = (bb * ask_vol + ba * bid_vol) / total_vol
            else:
                microprice = (bb + ba) / 2

            # Track history
            self.mid_history[symbol].append(microprice)
            self.mid_history[symbol] = self.mid_history[symbol][-VOL_WINDOW:]

            # Volatility
            vol = 2.0
            if len(self.mid_history[symbol]) >= 2:
                avg = sum(self.mid_history[symbol]) / len(self.mid_history[symbol])
                vol = max(
                    1.0,
                    math.sqrt(
                        sum((x - avg) ** 2 for x in self.mid_history[symbol])
                        / len(self.mid_history[symbol])
                    ),
                )

            # Fair value
            if symbol == "EMERALDS":
                fair = 10000.0
            else:
                if self.tom_ema is None:
                    self.tom_ema = microprice
                else:
                    prev = self.tom_ema
                    self.tom_ema = EMA_ALPHA * microprice + (1 - EMA_ALPHA) * self.tom_ema
                    self.tom_momentum = self.tom_ema - prev
                fair = self.tom_ema + self.tom_momentum * MOMENTUM_WEIGHT

            # OBI
            obi = (bid_vol - ask_vol) / total_vol if total_vol > 0 else 0

            # Adjusted fair
            adjusted_fair = fair - pos * SKEW_FACTOR + obi * 2
            edge = max(1, int(vol * EDGE_MULTIPLIER))

            # Generate orders
            symbol_orders: list[Order] = []

            # Snipe mispriced
            if fair - edge > bb:
                size = min(BASE_SIZE, int(BASE_SIZE * (fair - bb) / edge), 80 - pos)
                if size > 0:
                    symbol_orders.append(Order(symbol, bb, size))
            if fair + edge < ba:
                size = min(BASE_SIZE, int(BASE_SIZE * (ba - fair) / edge), 80 + pos)
                if size > 0:
                    symbol_orders.append(Order(symbol, ba, -size))

            # Penny quotes
            if ba - bb > 2:
                if abs(obi) < OBI_THRESHOLD or obi > 0:
                    ps = min(10, 80 - pos)
                    if ps > 0:
                        symbol_orders.append(Order(symbol, bb + 1, ps))
                if abs(obi) < OBI_THRESHOLD or obi < 0:
                    ps = min(10, 80 + pos)
                    if ps > 0:
                        symbol_orders.append(Order(symbol, ba - 1, -ps))

            orders[symbol] = symbol_orders

        return orders, 0, ""
