"""Dual-asset volatility-adaptive market maker — Prosperity 4 submission.

Generated by o4-mini (Round 9) + parameter sweep (ema_alpha=0.3).
Local backtest PnL: 10,655 (10K ticks).
Strategy: EMERALDS fixed FV=10000 with skew, TOMATOES vol-adaptive spreads
with z-score mean reversion overlay and aggressive unwind.
"""

import math

Time = int
Symbol = str
Product = str
Position = int
UserId = str
ObservationValue = int


class Listing:
    def __init__(self, symbol: Symbol, product: Product, denomination: Product) -> None:
        self.symbol = symbol
        self.product = product
        self.denomination = denomination


class ConversionObservation:
    def __init__(
        self,
        bidPrice: float,
        askPrice: float,
        transportFees: float,
        exportTariff: float,
        importTariff: float,
        sugarPrice: float,
        sunlightIndex: float,
    ) -> None:
        self.bidPrice = bidPrice
        self.askPrice = askPrice
        self.transportFees = transportFees
        self.exportTariff = exportTariff
        self.importTariff = importTariff
        self.sugarPrice = sugarPrice
        self.sunlightIndex = sunlightIndex


class Observation:
    def __init__(
        self,
        plainValueObservations: dict[Product, ObservationValue] | None = None,
        conversionObservations: dict[Product, ConversionObservation] | None = None,
    ) -> None:
        self.plainValueObservations = plainValueObservations or {}
        self.conversionObservations = conversionObservations or {}


class Order:
    def __init__(self, symbol: Symbol, price: int, quantity: int) -> None:
        self.symbol = symbol
        self.price = price
        self.quantity = quantity


class OrderDepth:
    def __init__(self) -> None:
        self.buy_orders: dict[int, int] = {}
        self.sell_orders: dict[int, int] = {}


class Trade:
    def __init__(
        self,
        symbol: Symbol,
        price: int,
        quantity: int,
        buyer: UserId = "",
        seller: UserId = "",
        timestamp: int = 0,
    ) -> None:
        self.symbol = symbol
        self.price = price
        self.quantity = quantity
        self.buyer = buyer
        self.seller = seller
        self.timestamp = timestamp


class TradingState:
    def __init__(
        self,
        timestamp: Time,
        traderData: str,
        listings: dict[Symbol, Listing],
        order_depths: dict[Symbol, OrderDepth],
        own_trades: dict[Symbol, list[Trade]],
        market_trades: dict[Symbol, list[Trade]],
        position: dict[Product, Position],
        observations: Observation,
    ) -> None:
        self.timestamp = timestamp
        self.traderData = traderData
        self.listings = listings
        self.order_depths = order_depths
        self.own_trades = own_trades
        self.market_trades = market_trades
        self.position = position
        self.observations = observations


# ---------------------------------------------------------------------------
# Strategy
# ---------------------------------------------------------------------------

EMA_ALPHA = 0.3
VOL_WINDOW = 30
VOL_THRESHOLD_MULT = 1.5


class Trader:
    def __init__(self) -> None:
        self.state_data: dict[str, dict] = {}

    def run(self, state: TradingState) -> tuple[dict[str, list[Order]], int, str]:
        orders: dict[str, list[Order]] = {}

        # EMERALDS: Fixed fair value market making
        if "EMERALDS" in state.order_depths:
            depth = state.order_depths["EMERALDS"]
            if depth.buy_orders and depth.sell_orders:
                pos = state.position.get("EMERALDS", 0)
                fair = 10000
                skew = int(pos * 0.3)
                bb = max(depth.buy_orders.keys())
                ba = min(depth.sell_orders.keys())
                buy_price = min(fair - 5 - skew, bb + 1)
                sell_price = max(fair + 5 - skew, ba - 1)
                orders["EMERALDS"] = [
                    Order("EMERALDS", buy_price, 19),
                    Order("EMERALDS", sell_price, -19),
                ]

        # TOMATOES: Volatility-adaptive market making
        if "TOMATOES" in state.order_depths:
            depth = state.order_depths["TOMATOES"]
            if depth.buy_orders and depth.sell_orders:
                bb = max(depth.buy_orders.keys())
                ba = min(depth.sell_orders.keys())
                mid = (bb + ba) / 2

                if "TOMATOES" not in self.state_data:
                    self.state_data["TOMATOES"] = {"ema": mid, "mids": [], "stds": []}

                data = self.state_data["TOMATOES"]
                data["ema"] = EMA_ALPHA * mid + (1 - EMA_ALPHA) * data["ema"]
                data["mids"].append(mid)
                data["mids"] = data["mids"][-VOL_WINDOW:]

                if len(data["mids"]) >= 2:
                    ema = data["ema"]
                    std = math.sqrt(sum((m - ema) ** 2 for m in data["mids"]) / len(data["mids"]))
                    data["stds"].append(std)
                    data["stds"] = data["stds"][-100:]

                    if len(data["stds"]) > 10:
                        median_std = sorted(data["stds"])[len(data["stds"]) // 2]
                        vol_threshold = VOL_THRESHOLD_MULT * median_std

                        if std < vol_threshold:
                            base_spread, order_size, skew_factor = 10, 15, 0.3
                        else:
                            base_spread, order_size, skew_factor = 14, 8, 0.2

                        pos = state.position.get("TOMATOES", 0)
                        skew = int(pos * skew_factor)
                        fair = int(ema)
                        buy_price = min(fair - base_spread // 2 - skew, bb + 1)
                        sell_price = max(fair + base_spread // 2 - skew, ba - 1)

                        orders["TOMATOES"] = [
                            Order("TOMATOES", buy_price, order_size),
                            Order("TOMATOES", sell_price, -order_size),
                        ]

                        # Mean-reversion overlay
                        if std > 0:
                            z_score = (mid - ema) / std
                            if z_score > 1.5:
                                orders["TOMATOES"].append(Order("TOMATOES", int(mid) - 1, -10))
                            elif z_score < -1.5:
                                orders["TOMATOES"].append(Order("TOMATOES", int(mid) + 1, 10))

                        # Aggressive unwind
                        if abs(pos) > 60:
                            unwind_price = fair - 1 if pos > 0 else fair + 1
                            unwind_size = -20 if pos > 0 else 20
                            orders["TOMATOES"].append(Order("TOMATOES", unwind_price, unwind_size))

        return orders, 0, ""
