"""Continuous unwind smart penny sniper — Prosperity 4 submission.

Generated by Gemini 3.1 Pro (Round 2) + sweep (unwind_threshold=60).
Local backtest PnL: 16,116 (10K ticks, jmerle matching).
Expected platform PnL: ~2,600 (6.2x ratio).
Strategy: Microprice + OBI fair value, momentum-weighted EMA,
continuous proportional unwind, smart pennying based on OBI+momentum direction.
"""

import math

Time = int
Symbol = str
Product = str
Position = int
UserId = str
ObservationValue = int


class Listing:
    def __init__(self, symbol: Symbol, product: Product, denomination: Product) -> None:
        self.symbol = symbol
        self.product = product
        self.denomination = denomination


class ConversionObservation:
    def __init__(
        self,
        bidPrice: float,
        askPrice: float,
        transportFees: float,
        exportTariff: float,
        importTariff: float,
        sugarPrice: float,
        sunlightIndex: float,
    ) -> None:
        self.bidPrice = bidPrice
        self.askPrice = askPrice
        self.transportFees = transportFees
        self.exportTariff = exportTariff
        self.importTariff = importTariff
        self.sugarPrice = sugarPrice
        self.sunlightIndex = sunlightIndex


class Observation:
    def __init__(
        self,
        plainValueObservations: dict[Product, ObservationValue] | None = None,
        conversionObservations: dict[Product, ConversionObservation] | None = None,
    ) -> None:
        self.plainValueObservations = plainValueObservations or {}
        self.conversionObservations = conversionObservations or {}


class Order:
    def __init__(self, symbol: Symbol, price: int, quantity: int) -> None:
        self.symbol = symbol
        self.price = price
        self.quantity = quantity


class OrderDepth:
    def __init__(self) -> None:
        self.buy_orders: dict[int, int] = {}
        self.sell_orders: dict[int, int] = {}


class Trade:
    def __init__(
        self,
        symbol: Symbol,
        price: int,
        quantity: int,
        buyer: UserId = "",
        seller: UserId = "",
        timestamp: int = 0,
    ) -> None:
        self.symbol = symbol
        self.price = price
        self.quantity = quantity
        self.buyer = buyer
        self.seller = seller
        self.timestamp = timestamp


class TradingState:
    def __init__(
        self,
        timestamp: Time,
        traderData: str,
        listings: dict[Symbol, Listing],
        order_depths: dict[Symbol, OrderDepth],
        own_trades: dict[Symbol, list[Trade]],
        market_trades: dict[Symbol, list[Trade]],
        position: dict[Product, Position],
        observations: Observation,
    ) -> None:
        self.timestamp = timestamp
        self.traderData = traderData
        self.listings = listings
        self.order_depths = order_depths
        self.own_trades = own_trades
        self.market_trades = market_trades
        self.position = position
        self.observations = observations


# ---------------------------------------------------------------------------
# Strategy
# ---------------------------------------------------------------------------

EMA_ALPHA = 0.15
MOMENTUM_WEIGHT = 0.2
INV_SKEW_FACTOR = 0.5
OBI_FACTOR = 0.3
VOL_WINDOW = 10
BASE_EDGE = 1.0
VOL_SCALE = 0.5
SIZE_SCALE = 0.8
UNWIND_THRESHOLD = 60
UNWIND_AGGRESSION = 0.3
MAX_SIZE = 15


class Trader:
    def __init__(self) -> None:
        self.ema_prices: dict[str, float] = {}
        self.price_history: dict[str, list[float]] = {}

    def run(self, state: TradingState) -> tuple[dict[str, list[Order]], int, str]:
        orders: dict[str, list[Order]] = {}

        for symbol, depth in state.order_depths.items():
            if not depth.buy_orders or not depth.sell_orders:
                continue

            bb = max(depth.buy_orders.keys())
            ba = min(depth.sell_orders.keys())
            mp = (bb + ba) / 2
            pos = state.position.get(symbol, 0)

            # Price history
            if symbol not in self.price_history:
                self.price_history[symbol] = []
            self.price_history[symbol].append(mp)
            if len(self.price_history[symbol]) > VOL_WINDOW:
                self.price_history[symbol].pop(0)

            # Fair value
            if symbol == "EMERALDS":
                fv = 10000.0
            else:
                if symbol not in self.ema_prices:
                    self.ema_prices[symbol] = mp
                self.ema_prices[symbol] = EMA_ALPHA * mp + (1 - EMA_ALPHA) * self.ema_prices[symbol]
                momentum = mp - self.ema_prices[symbol]
                fv = self.ema_prices[symbol] + momentum * MOMENTUM_WEIGHT

            # OBI
            bid_vol = sum(depth.buy_orders.values())
            ask_vol = sum(-v for v in depth.sell_orders.values())
            total_vol = bid_vol + ask_vol
            obi = (bid_vol - ask_vol) / total_vol if total_vol > 0 else 0
            adj_fv = fv - pos * INV_SKEW_FACTOR + obi * OBI_FACTOR

            # Volatility
            vol = 1.0
            if len(self.price_history[symbol]) > 1:
                avg = sum(self.price_history[symbol]) / len(self.price_history[symbol])
                vol = max(
                    1.0,
                    math.sqrt(
                        sum((p - avg) ** 2 for p in self.price_history[symbol])
                        / len(self.price_history[symbol])
                    ),
                )
            edge = BASE_EDGE + vol * VOL_SCALE

            symbol_orders: list[Order] = []
            spread = ba - bb

            # Continuous unwind
            if abs(pos) > UNWIND_THRESHOLD:
                excess = abs(pos) - UNWIND_THRESHOLD
                unwind_size = min(int(excess * UNWIND_AGGRESSION), MAX_SIZE)
                if unwind_size > 0:
                    if pos > UNWIND_THRESHOLD:
                        symbol_orders.append(Order(symbol, bb, -unwind_size))
                    else:
                        symbol_orders.append(Order(symbol, ba, unwind_size))

            # Smart pennying
            if spread > 1:
                momentum = mp - self.ema_prices.get(symbol, mp)
                if obi > 0.1 and momentum > 0:
                    buy_price = bb + 1
                    sell_price = ba
                elif obi < -0.1 and momentum < 0:
                    buy_price = bb
                    sell_price = ba - 1
                else:
                    buy_price = bb + 1 if adj_fv > mp else bb
                    sell_price = ba - 1 if adj_fv < mp else ba
            else:
                buy_price = int(adj_fv - edge)
                sell_price = int(adj_fv + edge)

            # Sizing
            buy_dist = max(1, adj_fv - buy_price)
            sell_dist = max(1, sell_price - adj_fv)
            buy_size = max(5, min(int(MAX_SIZE * (1 - buy_dist / 100) * SIZE_SCALE), MAX_SIZE))
            sell_size = max(5, min(int(MAX_SIZE * (1 - sell_dist / 100) * SIZE_SCALE), MAX_SIZE))

            if pos <= UNWIND_THRESHOLD:
                symbol_orders.append(Order(symbol, buy_price, buy_size))
            if pos >= -UNWIND_THRESHOLD:
                symbol_orders.append(Order(symbol, sell_price, -sell_size))

            orders[symbol] = symbol_orders

        return orders, 0, ""
