"""Sniper + pennying dual market maker — Prosperity 4 submission.

Generated by Gemini 3.1 Pro (Round 4) + sweep (ema_alpha=0.25).
Local backtest PnL: 15,072 (10K ticks, jmerle semantics, ~3000 expected on platform).
Strategy: Snipes mispriced orders from the book, then pennies the spread.
Two-phase order generation with inventory skew and aggressive unwind.
"""

Time = int
Symbol = str
Product = str
Position = int
UserId = str
ObservationValue = int


class Listing:
    def __init__(self, symbol: Symbol, product: Product, denomination: Product) -> None:
        self.symbol = symbol
        self.product = product
        self.denomination = denomination


class ConversionObservation:
    def __init__(
        self,
        bidPrice: float,
        askPrice: float,
        transportFees: float,
        exportTariff: float,
        importTariff: float,
        sugarPrice: float,
        sunlightIndex: float,
    ) -> None:
        self.bidPrice = bidPrice
        self.askPrice = askPrice
        self.transportFees = transportFees
        self.exportTariff = exportTariff
        self.importTariff = importTariff
        self.sugarPrice = sugarPrice
        self.sunlightIndex = sunlightIndex


class Observation:
    def __init__(
        self,
        plainValueObservations: dict[Product, ObservationValue] | None = None,
        conversionObservations: dict[Product, ConversionObservation] | None = None,
    ) -> None:
        self.plainValueObservations = plainValueObservations or {}
        self.conversionObservations = conversionObservations or {}


class Order:
    def __init__(self, symbol: Symbol, price: int, quantity: int) -> None:
        self.symbol = symbol
        self.price = price
        self.quantity = quantity


class OrderDepth:
    def __init__(self) -> None:
        self.buy_orders: dict[int, int] = {}
        self.sell_orders: dict[int, int] = {}


class Trade:
    def __init__(
        self,
        symbol: Symbol,
        price: int,
        quantity: int,
        buyer: UserId = "",
        seller: UserId = "",
        timestamp: int = 0,
    ) -> None:
        self.symbol = symbol
        self.price = price
        self.quantity = quantity
        self.buyer = buyer
        self.seller = seller
        self.timestamp = timestamp


class TradingState:
    def __init__(
        self,
        timestamp: Time,
        traderData: str,
        listings: dict[Symbol, Listing],
        order_depths: dict[Symbol, OrderDepth],
        own_trades: dict[Symbol, list[Trade]],
        market_trades: dict[Symbol, list[Trade]],
        position: dict[Product, Position],
        observations: Observation,
    ) -> None:
        self.timestamp = timestamp
        self.traderData = traderData
        self.listings = listings
        self.order_depths = order_depths
        self.own_trades = own_trades
        self.market_trades = market_trades
        self.position = position
        self.observations = observations


# ---------------------------------------------------------------------------
# Strategy
# ---------------------------------------------------------------------------

ORDER_SIZE = 15
SKEW_FACTOR = 0.5
TAKE_EDGE = 1.0
MAKE_EDGE = 1.5
UNWIND_THRESHOLD = 55
EMA_ALPHA = 0.25


class Trader:
    def __init__(self) -> None:
        self.fair_values: dict[str, float] = {}

    def run(self, state: TradingState) -> tuple[dict[str, list[Order]], int, str]:
        orders: dict[str, list[Order]] = {}

        for symbol, depth in state.order_depths.items():
            if not depth.buy_orders or not depth.sell_orders:
                continue

            pos = state.position.get(symbol, 0)
            fair = self._get_fair_value(symbol, depth)
            if fair is None:
                continue

            skew = pos * SKEW_FACTOR
            adj_fair = fair - skew

            symbol_orders: list[Order] = []
            remaining_buy = ORDER_SIZE
            remaining_sell = ORDER_SIZE

            # Phase 1: Snipe mispriced orders from the book
            for price in sorted(depth.sell_orders.keys()):
                if price <= adj_fair - TAKE_EDGE and remaining_buy > 0:
                    qty = abs(depth.sell_orders[price])
                    size = min(qty, remaining_buy)
                    symbol_orders.append(Order(symbol, price, size))
                    remaining_buy -= size

            for price in sorted(depth.buy_orders.keys(), reverse=True):
                if price >= adj_fair + TAKE_EDGE and remaining_sell > 0:
                    qty = depth.buy_orders[price]
                    size = min(qty, remaining_sell)
                    symbol_orders.append(Order(symbol, price, -size))
                    remaining_sell -= size

            # Phase 2: Penny the spread
            bb = max(depth.buy_orders.keys())
            ba = min(depth.sell_orders.keys())

            if remaining_buy > 0 and bb + 1 <= adj_fair - MAKE_EDGE:
                symbol_orders.append(Order(symbol, bb + 1, remaining_buy))
            if remaining_sell > 0 and ba - 1 >= adj_fair + MAKE_EDGE:
                symbol_orders.append(Order(symbol, ba - 1, -remaining_sell))

            # Phase 3: Aggressive unwind if needed
            if abs(pos) > UNWIND_THRESHOLD:
                if pos > 0:
                    symbol_orders.append(Order(symbol, ba - 2, -min(20, pos)))
                elif pos < 0:
                    symbol_orders.append(Order(symbol, bb + 2, min(20, -pos)))

            orders[symbol] = symbol_orders

        return orders, 0, ""

    def _get_fair_value(self, symbol: str, depth: OrderDepth) -> float | None:
        if symbol == "EMERALDS":
            return 10000.0
        if not depth.buy_orders or not depth.sell_orders:
            return None
        bb = max(depth.buy_orders.keys())
        ba = min(depth.sell_orders.keys())
        mid = (bb + ba) / 2
        if symbol not in self.fair_values:
            self.fair_values[symbol] = mid
        else:
            self.fair_values[symbol] = EMA_ALPHA * mid + (1 - EMA_ALPHA) * self.fair_values[symbol]
        return self.fair_values[symbol]
