"""Pipeline top1: agent_r3_bifurcated_em_taker_tom_micro_sniper_variant_3, transfer=0.8458, pnl=15179"""

"""Volatility-adaptive microprice sniper — Prosperity 4 submission.

Generated by Gemini 3.1 Pro (Round 4), jmerle-compatible backtester.
Local backtest PnL: 15,503 (10K ticks, jmerle matching).
Expected platform PnL: ~2,770 (5.6x ratio).
Strategy: Microprice fair value, OBI-adjusted, momentum-weighted EMA,
volatility-adaptive edge, pennying + sniping, aggressive unwind.
"""


Time = int
Symbol = str
Product = str
Position = int
UserId = str
ObservationValue = int


class Listing:
    def __init__(self, symbol: Symbol, product: Product, denomination: Product) -> None:
        self.symbol = symbol
        self.product = product
        self.denomination = denomination


class ConversionObservation:
    def __init__(
        self,
        bidPrice: float,
        askPrice: float,
        transportFees: float,
        exportTariff: float,
        importTariff: float,
        sugarPrice: float,
        sunlightIndex: float,
    ) -> None:
        self.bidPrice = bidPrice
        self.askPrice = askPrice
        self.transportFees = transportFees
        self.exportTariff = exportTariff
        self.importTariff = importTariff
        self.sugarPrice = sugarPrice
        self.sunlightIndex = sunlightIndex


class Observation:
    def __init__(
        self,
        plainValueObservations: dict[Product, ObservationValue] | None = None,
        conversionObservations: dict[Product, ConversionObservation] | None = None,
    ) -> None:
        self.plainValueObservations = plainValueObservations or {}
        self.conversionObservations = conversionObservations or {}


class Order:
    def __init__(self, symbol: Symbol, price: int, quantity: int) -> None:
        self.symbol = symbol
        self.price = price
        self.quantity = quantity


class OrderDepth:
    def __init__(self) -> None:
        self.buy_orders: dict[int, int] = {}
        self.sell_orders: dict[int, int] = {}


class Trade:
    def __init__(
        self,
        symbol: Symbol,
        price: int,
        quantity: int,
        buyer: UserId = "",
        seller: UserId = "",
        timestamp: int = 0,
    ) -> None:
        self.symbol = symbol
        self.price = price
        self.quantity = quantity
        self.buyer = buyer
        self.seller = seller
        self.timestamp = timestamp


class TradingState:
    def __init__(
        self,
        timestamp: Time,
        traderData: str,
        listings: dict[Symbol, Listing],
        order_depths: dict[Symbol, OrderDepth],
        own_trades: dict[Symbol, list[Trade]],
        market_trades: dict[Symbol, list[Trade]],
        position: dict[Product, Position],
        observations: Observation,
    ) -> None:
        self.timestamp = timestamp
        self.traderData = traderData
        self.listings = listings
        self.order_depths = order_depths
        self.own_trades = own_trades
        self.market_trades = market_trades
        self.position = position
        self.observations = observations


# ---------------------------------------------------------------------------
# Strategy
# ---------------------------------------------------------------------------


class Trader:
    """Asset-specific hybrid strategy maximizing per-asset fills."""

    def __init__(self, params: dict | None = None) -> None:
        p = params or {}
        self.order_size: int = int(p.get("order_size", 14))
        self.unwind_threshold: int = int(p.get("unwind_threshold", 57))
        self.tom_alpha: float = float(p.get("tom_alpha", 0.1723))
        self.tom_skew_factor: float = float(p.get("tom_skew_factor", 0.2973))
        self.tom_obi_threshold: float = float(p.get("tom_obi_threshold", 0.2752))
        self.tom_vol_edge: int = int(p.get("tom_vol_edge", 3))
        self.tom_ema: dict[str, float] = {}

    def compute_orders(self, state: TradingState) -> dict[str, list[Order]]:
        orders: dict[str, list[Order]] = {}
        for symbol, depth in state.order_depths.items():
            position = state.position.get(symbol, 0)
            if abs(position) > self.unwind_threshold:
                orders[symbol] = self._unwind_orders(symbol, depth, position)
                continue
            if symbol == "EMERALDS":
                orders[symbol] = self._emerald_orders(depth, position)
            elif symbol == "TOMATOES":
                orders[symbol] = self._tomato_orders(symbol, depth, position)
        return orders

    def _emerald_orders(self, depth, position: int) -> list[Order]:
        bb, ba = max(depth.buy_orders.keys()), min(depth.sell_orders.keys())
        if bb is None or ba is None:
            return []
        buy_price = min(bb + 1, 9999)
        sell_price = max(ba - 1, 10001)
        return [
            Order("EMERALDS", buy_price, self.order_size),
            Order("EMERALDS", sell_price, -self.order_size),
        ]

    def _tomato_orders(self, symbol: str, depth, position: int) -> list[Order]:
        microprice = self._volume_weighted_microprice(depth)
        if microprice is None:
            return []
        fair = self.tom_ema.get(symbol, microprice)
        self.tom_ema[symbol] = self.tom_alpha * microprice + (1 - self.tom_alpha) * fair
        skew = -position * self.tom_skew_factor
        fair += skew
        obi = self._order_book_imbalance(depth)
        bb, ba = max(depth.buy_orders.keys()), min(depth.sell_orders.keys())
        if bb is None or ba is None:
            return []
        orders = []
        if abs(obi) < self.tom_obi_threshold:
            orders.append(Order(symbol, bb + 1, self.order_size))
            orders.append(Order(symbol, ba - 1, -self.order_size))
        edge = self.tom_vol_edge * max(1, int((ba - bb) / 4))
        orders.append(Order(symbol, int(fair - edge), self.order_size))
        orders.append(Order(symbol, int(fair + edge), -self.order_size))
        return orders

    def _unwind_orders(self, symbol: str, depth, position: int) -> list[Order]:
        bb, ba = max(depth.buy_orders.keys()), min(depth.sell_orders.keys())
        if position > 0 and bb is not None:
            return [Order(symbol, bb, -min(position, 20))]
        elif position < 0 and ba is not None:
            return [Order(symbol, ba, min(-position, 20))]
        return []

    def _volume_weighted_microprice(self, depth) -> float | None:
        bb, ba = max(depth.buy_orders.keys()), min(depth.sell_orders.keys())
        if bb is None or ba is None:
            return None
        bv = depth.buy_orders.get(bb, 0)
        av = -depth.sell_orders.get(ba, 0)
        return (bb * av + ba * bv) / (bv + av) if bv + av > 0 else (bb + ba) / 2

    def _order_book_imbalance(self, depth) -> float:
        bb, ba = max(depth.buy_orders.keys()), min(depth.sell_orders.keys())
        if bb is None or ba is None:
            return 0
        bv = depth.buy_orders.get(bb, 0)
        av = -depth.sell_orders.get(ba, 0)
        return (bv - av) / (bv + av) if bv + av > 0 else 0

    def run(self, state):
        return self.compute_orders(state), 0, ""
