"""Pipeline new_best: agent_r8_bifurcated_smart_penny_sniper, transfer=0.6431, pnl=15683"""

"""Volatility-adaptive microprice sniper — Prosperity 4 submission.

Generated by Gemini 3.1 Pro (Round 4), jmerle-compatible backtester.
Local backtest PnL: 15,503 (10K ticks, jmerle matching).
Expected platform PnL: ~2,770 (5.6x ratio).
Strategy: Microprice fair value, OBI-adjusted, momentum-weighted EMA,
volatility-adaptive edge, pennying + sniping, aggressive unwind.
"""


Time = int
Symbol = str
Product = str
Position = int
UserId = str
ObservationValue = int


class Listing:
    def __init__(self, symbol: Symbol, product: Product, denomination: Product) -> None:
        self.symbol = symbol
        self.product = product
        self.denomination = denomination


class ConversionObservation:
    def __init__(
        self,
        bidPrice: float,
        askPrice: float,
        transportFees: float,
        exportTariff: float,
        importTariff: float,
        sugarPrice: float,
        sunlightIndex: float,
    ) -> None:
        self.bidPrice = bidPrice
        self.askPrice = askPrice
        self.transportFees = transportFees
        self.exportTariff = exportTariff
        self.importTariff = importTariff
        self.sugarPrice = sugarPrice
        self.sunlightIndex = sunlightIndex


class Observation:
    def __init__(
        self,
        plainValueObservations: dict[Product, ObservationValue] | None = None,
        conversionObservations: dict[Product, ConversionObservation] | None = None,
    ) -> None:
        self.plainValueObservations = plainValueObservations or {}
        self.conversionObservations = conversionObservations or {}


class Order:
    def __init__(self, symbol: Symbol, price: int, quantity: int) -> None:
        self.symbol = symbol
        self.price = price
        self.quantity = quantity


class OrderDepth:
    def __init__(self) -> None:
        self.buy_orders: dict[int, int] = {}
        self.sell_orders: dict[int, int] = {}


class Trade:
    def __init__(
        self,
        symbol: Symbol,
        price: int,
        quantity: int,
        buyer: UserId = "",
        seller: UserId = "",
        timestamp: int = 0,
    ) -> None:
        self.symbol = symbol
        self.price = price
        self.quantity = quantity
        self.buyer = buyer
        self.seller = seller
        self.timestamp = timestamp


class TradingState:
    def __init__(
        self,
        timestamp: Time,
        traderData: str,
        listings: dict[Symbol, Listing],
        order_depths: dict[Symbol, OrderDepth],
        own_trades: dict[Symbol, list[Trade]],
        market_trades: dict[Symbol, list[Trade]],
        position: dict[Product, Position],
        observations: Observation,
    ) -> None:
        self.timestamp = timestamp
        self.traderData = traderData
        self.listings = listings
        self.order_depths = order_depths
        self.own_trades = own_trades
        self.market_trades = market_trades
        self.position = position
        self.observations = observations


# ---------------------------------------------------------------------------
# Strategy
# ---------------------------------------------------------------------------


class Trader:
    """Asset-specific fair value with inventory skew, smart pennying, and aggressive taker unwinding."""

    def __init__(self, params: dict | None = None) -> None:
        p = params or {}
        # Stationary assets
        self.emeralds_fair = int(p.get("emeralds_fair", 10000))
        self.emeralds_edge = int(p.get("emeralds_edge", 2))
        self.emeralds_skew_factor = float(p.get("emeralds_skew_factor", 0.2))

        # Drifting assets
        self.tomatoes_edge = float(p.get("tomatoes_edge", 1.5))
        self.tomatoes_skew_factor = float(p.get("tomatoes_skew_factor", 0.3))
        self.ema_alpha = float(p.get("ema_alpha", 0.15))

        # Common params
        self.order_size = int(p.get("order_size", 15))
        self.unwind_threshold = int(p.get("unwind_threshold", 50))

        # EMA storage
        self.emas: dict[str, float] = {}

    def compute_orders(self, state: TradingState) -> dict[str, list[Order]]:
        """Compute orders for all assets with bifurcated logic."""
        orders: dict[str, list[Order]] = {}

        for symbol, depth in state.order_depths.items():
            if not depth.buy_orders or not depth.sell_orders:
                continue

            symbol_orders = []
            position = state.position.get(symbol, 0)

            # Get market quotes
            bid = max(depth.buy_orders.keys())
            ask = min(depth.sell_orders.keys())
            if bid is None or ask is None:
                continue

            bid_vol = sum(depth.buy_orders.values())
            ask_vol = -sum(depth.sell_orders.values())

            # Unwind logic first (for all assets)
            if position > self.unwind_threshold:
                # Aggressive sell
                sell_size = min(self.order_size, position)
                symbol_orders.append(Order(symbol, bid, -sell_size))
                # Skip normal buy quotes
                orders[symbol] = symbol_orders
                continue
            elif position < -self.unwind_threshold:
                # Aggressive buy
                buy_size = min(self.order_size, -position)
                symbol_orders.append(Order(symbol, ask, buy_size))
                # Skip normal sell quotes
                orders[symbol] = symbol_orders
                continue

            # Asset-specific logic
            if symbol == "EMERALDS":
                # Stationary asset logic
                fair_value = self.emeralds_fair
                skew = int(position * self.emeralds_skew_factor)
                desired_buy = fair_value - self.emeralds_edge - skew
                desired_sell = fair_value + self.emeralds_edge - skew

                # Snipe logic
                if ask <= desired_buy:
                    size = min(self.order_size, ask_vol)
                    symbol_orders.append(Order(symbol, ask, size))
                if bid >= desired_sell:
                    size = min(self.order_size, bid_vol)
                    symbol_orders.append(Order(symbol, bid, -size))

                # Maker logic
                penny_buy = min(bid + 1, desired_buy)
                penny_sell = max(ask - 1, desired_sell)
                symbol_orders.append(Order(symbol, penny_buy, self.order_size))
                symbol_orders.append(Order(symbol, penny_sell, -self.order_size))

            elif symbol == "TOMATOES":
                # Drifting asset logic
                # Calculate microprice
                total_vol = bid_vol + ask_vol
                if total_vol > 0:
                    microprice = (bid * ask_vol + ask * bid_vol) / total_vol
                else:
                    microprice = (bid + ask) / 2

                # Update EMA
                if symbol in self.emas:
                    ema = self.ema_alpha * microprice + (1 - self.ema_alpha) * self.emas[symbol]
                else:
                    ema = microprice
                self.emas[symbol] = ema

                fair_value = ema
                skew = position * self.tomatoes_skew_factor
                desired_buy = fair_value - self.tomatoes_edge - skew
                desired_sell = fair_value + self.tomatoes_edge - skew

                # Snipe logic
                if ask <= desired_buy:
                    size = min(self.order_size, ask_vol)
                    symbol_orders.append(Order(symbol, ask, size))
                if bid >= desired_sell:
                    size = min(self.order_size, bid_vol)
                    symbol_orders.append(Order(symbol, bid, -size))

                # Maker logic
                penny_buy = min(bid + 1, int(desired_buy))
                penny_sell = max(ask - 1, int(desired_sell))
                symbol_orders.append(Order(symbol, penny_buy, self.order_size))
                symbol_orders.append(Order(symbol, penny_sell, -self.order_size))

            orders[symbol] = symbol_orders

        return orders

    def run(self, state):
        return self.compute_orders(state), 0, ""
